### ISSUE TITLE
how to work with cucumber?

### ISSUE THREAD

**Issue by huang12zheng** [mitsuhiko/insta#235] opened 2022-07-12 22:41 UTC
### What happened?

* cargo insta test  error
```sh
cargo insta test   
    Finished test [unoptimized + debuginfo] target(s) in 0.37s
     Running tests/main.rs (target/debug/deps/main-655db0c9f854f61a)
error: Found argument '-q' which wasn't expected, or isn't valid in this context

        If you tried to supply `-q` as a value rather than a flag, use `-- -q`
```
* `cargo test` would work
---
>  I did a quick check and found that parameters were added, But I don't know if that's it
> [cli](https://github.com/mitsuhiko/insta/blob/master/cargo-insta/src/cli.rs#L560-L561)
> ```
>   proc.arg("--");
>   proc.arg("-q");
> ```

### Reproduction steps

1. git clone --branch insta_with_cucumber https://github.com/huang12zheng/insta_issue
2. cargo insta test

### Insta Version

insta = "1.15.0"

### rustc Version

1.59

### What did you expect?

pass test
Is the '-q' needed?

**Comment by max-sixty** [comment] 2022-07-12 23:05
This seems like a dupe of https://github.com/mitsuhiko/insta/issues/234?

**Comment by huang12zheng** [comment] 2022-07-12 23:07
@max-sixty  This has nothing to do with that

**Comment by huang12zheng** [comment] 2022-07-12 23:08
INSTA_UPDATE=1 cargo test
would work
But I don't know if I should

**Comment by max-sixty** [comment] 2022-07-12 23:12
Is the link above to this issue or #234? I see https://github.com/huang12zheng/insta_issue/blob/main/src/main.rs at that link?

**Comment by huang12zheng** [comment] 2022-07-12 23:15
Sorry, I added arg --branch insta_with_cucumber for git clone
Are you confused because of this?

**Comment by max-sixty** [comment] 2022-07-13 00:23
Ah I see, sorry for the confusion.

Yes, I can repro. The `-q` is coming from https://github.com/mitsuhiko/insta/blob/master/cargo-insta/src/cli.rs#L561. I'm not sure why there's a conflict here yet.

**Comment by mitsuhiko** [comment] 2022-07-16 09:46
I believe this is a bug in cucumber. What insta tries to do is this:

```
cargo test --no-fail-fast --color auto -- -- -q
```

You can see from the output that the suggestion for how to fix this is already what we do:

```
you tried to supply `-q` as a value rather than a flag, use `-- -q`
```

There is probably an option I can add to remove the `-q` but ultimately I would propose filing this against cucumber.

**Comment by mitsuhiko** [comment] 2022-07-21 21:40
I believe this is sufficiently resolved. Cucumber however ideally learns about the `-q` flag then the workaround from #236 is not needed.

**Closed by mitsuhiko** 2022-07-21 21:40 UTC
Labels: bug
