### ISSUE TITLE
Support for files with (or without) diffing

### ISSUE THREAD

**Issue by bjchambers** [mitsuhiko/insta#190] opened 2021-08-11 22:24 UTC
It would be helpful if `insta` could also be used for managing file contents. For instance, some tests may produce CSV (and the plain text / diffing based on strings i great), but if other tests want to produce Parquet files (a binary format) they can't use insta.

How difficult would it be to have something like `insta::assert_binary_file(<path>)` and `insta::assert_text_file(<path>)`?

**Comment by mitsuhiko** [comment] 2021-08-16 14:45
What would the behavior of this be when the mismatch happens?

**Comment by bjchambers** [comment] 2021-08-16 14:52
It could be similar to https://docs.rs/goldenfile/1.1.0/goldenfile/ - output the diff (or diff hashes if the files are binary) and allow accepting to overwrite the expected file (or hash).

**Comment by mitsuhiko** [comment] 2021-08-16 15:03
I would be accepting a patch for it but I assume the work required would be quite significant since everything in the system currently assumes unicode strings.

**Comment by mitsuhiko** [comment] 2021-12-24 07:53
Closing this as duplicate of #196

**Closed by mitsuhiko** 2021-12-24 07:53 UTC
