### ISSUE TITLE
`--delete-unreferenced-snapshots` does not delete .snap files ignored by .gitignore/.ignore

### ISSUE THREAD

**Issue by aminya** [mitsuhiko/insta#277] opened 2022-08-26 03:09 UTC
### What happened?

I expected `--delete-unreferenced-snapshots` to delete all the snap files under the snapshots folder that are not used in the tests, but apparently, this has no effect.

### Reproduction steps

1. create a snap file under the snapshots folder
2. run `cargo insta test --delete-unreferenced-snapshots`
3. See the snap file not being removed

### Insta Version

1.19.0

### rustc Version

rustc 1.64.0-nightly (1b57946a4 2022-08-03)

### What did you expect?

Removal of excess snap files

**Comment by mitsuhiko** [comment] 2022-08-26 09:58
Did the tests pass or did the process fail with an error? The deletion will only happen if all tests passed.

**Comment by aminya** [comment] 2022-08-26 10:02
The tests passed. I used `insta test --review --delete-unreferenced-snapshots  --accept-unseen` command

**Comment by mitsuhiko** [comment] 2022-08-30 07:40
I cannot reproduce this. The command works for me. Can you create a test case in a repo that shows the issue?

**Comment by aminya** [comment] 2022-08-30 09:23
Here you go. I think the trick is to add the snap files to the `gitignore`. That apparently breaks the flag.

https://github.com/aminya/insta-unreferenced-bug

**Comment by mitsuhiko** [comment] 2022-08-31 07:23
That makes sense. This is very much intentional to ignore files which are not tracked in version control. The assumption is that this does not happen in practice. I will change the description of the issue.

**Comment by max-sixty** [comment] 2023-04-10 21:55
I think this can be closed as completed now we have `include_ignored`?

**Closed** 2023-04-16 22:16 UTC
Labels: bug, need-more-info
