### ISSUE TITLE
Too many calls to `insta::assert_debug_snapshot!` in a test case panics

### ISSUE THREAD

**Issue by kevinbarabash** [mitsuhiko/insta#254] opened 2022-07-30 16:14 UTC
### What happened?

I had a test case where I kept adding more calls to `insta::assert_debug_snapshot!`.  This isn't a good way to structure tests since if there's a failure it's hard to know which snapshot caused the failure.  Regardless, it's a way to write tests very quickly.  When I added too many calls to `insta::assert_debug_snapshot!` I saw a panic I wasn't expecting.  Reducing the number of calls to `insta::assert_debug_snapshot!` fixed the panic.

### Reproduction steps

1. Write a test with more than 10 calls to `insta::assert_debug_snapshot!`.
2. See a panic that looks similar to the logs snippet below:
```
---- type_ann::tests::type_annotations stdout ----
thread 'type_ann::tests::type_annotations' panicked at 'called `Result::unwrap()` on an `Err` value: Scan(ScanError { mark: Marker { index: 50, line: 3, col: 0 }, info: "while parsing a block mapping, did not find expected key" })', crates/crochet_parser/src/type_ann.rs:187:9
```

### Insta Version

1.13.0

### rustc Version

1.62.1

### What did you expect?

I expected `insta::assert_debug_snapshot!` not to panic regardless of how many calls I had in a single test case.

**Comment by max-sixty** [comment] 2022-07-30 19:03
I have lots of tests with more than ten calls. Could it be something to do with the underlying library? Is there a repo that can reproduce this?

**Comment by mitsuhiko** [comment] 2022-07-30 20:30
Considering you are getting a panic in `crochet_parser` which is not a dependency from insta I am going to close this as invalid. There is a chance that insta is involved here, but I'm entirely unable to reproduce this.

**Closed by mitsuhiko** 2022-07-30 20:30 UTC
Labels: bug
